In [1]:
import unicodecsv

#read data from CSV file and make it to lists
def read_csv(filename):
    with open(filename, 'rb') as f:
        reader = unicodecsv.DictReader(f)
        return list(reader)

In [2]:
order = read_csv('../data_20180120/order.csv')

เลขที่คำสั่งซื้อ (Order_ID)

In [3]:
import pandas as pd

pd.DataFrame(order)

,"﻿""ORDER_ID""",CUSTOMER_ID,BPCODE,CREATE_DATE,UPDATE_DATE,STATUS
0,"2,024",22,1100700373,2015-10-05 21:05:45,2015-10-05 21:05:45,PENDING
1,"2,241","4,122",1100702444,2015-10-15 18:51:08,2015-10-15 19:03:44,PENDING
2,"2,321","4,223",1100702550,2015-10-16 15:36:42,2015-10-16 15:42:23,PAID_SUCCESS
3,"2,341","4,122",1100702444,2015-10-16 23:45:30,2015-10-16 23:54:33,PENDING
4,"2,422","4,527",1100702884,2015-10-17 18:35:16,2015-10-17 18:45:13,PENDING
5,"2,442","4,462",1100702709,2015-10-18 15:41:07,2015-10-18 15:50:14,PENDING
6,"2,481","2,509",1100605014,2015-10-18 20:50:15,2015-10-18 20:58:13,PAID_SUCCESS
7,"2,561","2,784",1100686150,2015-10-20 13:37:30,2015-10-20 13:45:41,PENDING
8,"2,641","5,509",1100703880,2015-10-22 13:34:21,2015-10-22 13:44:58,PENDING
9,"2,682","5,805",1100704086,2015-10-23 13:38:16,2015-10-23 13:38:16,PENDING
10,"2,781","5,445",1100703863,2015-10-26 11:22:23,2015-10-26 11:25:26,PAID_SUCCESS
11,"3,121","8,064",1100662011,2015-10-31 16:47:46,2015-10-31 16:47:46,PENDING
12,"3,202","8,263",1100561933,2015-11-01 16:44:23,2015-11-01 16:46:12,PAID_SUCCESS
13,"3,261","8,525",1100704444,2015-11-02 16:43:18,2015-11-02 16:50:34,PENDING
14,"3,262","8,529",1100706894,2015-11-02 16:52:58,2015-11-02 16:52:58,PENDING
15,"3,341","8,724",1100707006,2015-11-03 16:47:02,2015-11-03 16:55:40,PENDING
16,"3,403","2,429",1100697318,2015-11-04 14:44:23,2015-11-04 14:55:43,PENDING
17,"3,461","9,104",1100707277,2015-11-05 23:49:50,2015-11-05 23:49:50,PENDING
18,"3,681","4,802",1100707987,2015-11-08 14:23:58,2015-11-08 14:31:09,PENDING
19,"3,781","10,366",1100708439,2015-11-09 20:58:15,2015-11-09 20:58:15,PENDING
20,"3,962","10,702",1100708595,2015-11-11 10:22:41,2015-11-11 10:33:29,PAID_SUCCESS
21,"4,001","10,722",1100708626,2015-11-11 13:44:02,2015-11-12 13:53:06,PAID_SUCCESS
22,"4,021","10,782",1100708678,2015-11-11 16:00:42,2015-11-11 16:06:57,PENDING
23,"4,101","10,955",1100708795,2015-11-12 10:11:15,2015-11-12 10:27:45,PENDING_TMN_CREATED
24,"4,121","11,062",1100708914,2015-11-12 18:46:31,2015-11-12 18:46:57,PENDING_TMN_CREATED
25,"4,221","11,162",1100708972,2015-11-14 00:16:34,2015-11-14 00:18:17,PENDING_TMN_CREATED
26,"4,461","11,804",1100655391,2015-11-16 18:46:49,2015-11-16 18:52:36,PAID_SUCCESS
27,"4,621","12,070",1100710283,2015-11-17 20:58:10,2015-11-17 21:11:13,PENDING_TMN_CREATED
28,"4,701","12,142",1100710303,2015-11-18 10:41:48,2015-11-19 13:49:31,PAID_SUCCESS
29,"4,941","12,863",1100710868,2015-11-21 08:39:49,2015-11-21 08:42:02,PAID_SUCCESS
...,...,...,...,...,...,...
11923,"105,821","188,883",1100881820,2017-10-10 19:17:49,2017-10-10 19:17:49,PENDING
11924,"105,842","184,782",1100881270,2017-10-10 20:00:48,2017-10-10 23:33:33,PAID_SUCCESS
11925,"105,901","27,468",1100731690,2017-10-10 21:03:28,2017-10-10 21:21:12,PAID_SUCCESS
11926,"108,861","195,142",1100883956,2017-10-21 02:12:35,2017-10-21 10:53:18,PAID_SUCCESS
11927,"108,882","121,343",1100559973,2017-10-21 08:46:30,2017-10-21 08:53:17,PAID_SUCCESS
11928,"108,941","197,902",1100884598,2017-10-21 11:42:33,2017-10-21 11:42:33,PENDING
11929,"109,282","199,222",1100885270,2017-10-22 22:09:34,2017-10-22 22:09:34,PENDING
11930,"109,982","2,082",1100500779,2017-10-25 16:57:14,2017-10-25 16:57:14,PENDING
11931,"112,081","205,142",1100887427,2017-11-01 15:58:57,2017-11-01 15:58:57,PENDING
11932,"112,401","206,362",1100887613,2017-11-02 12:18:49,2017-11-02 12:18:49,PENDING
11933,"113,741","209,022",1100888598,2017-11-06 14:14:01,2017-11-06 14:14:01,PENDING
11934,"115,701","212,963",1100889388,2017-11-10 20:07:54,2017-11-11 06:37:18,PAID_SUCCESS
11935,"116,061","152,723",1100889427,2017-11-11 06:27:29,2017-11-11 06:27:08,CANCEL
11936,"116,205","176,764",1100787082,2017-11-11 08:26:59,2017-11-11 08:26:59,PENDING
11937,"116,941","204,802",1100887269,2017-11-11 14:37:58,2017-11-11 14:42:11,CANCEL
11938,"118,164","215,483",1100889933,2017-11-11 21:49:36,2017-11-11 22:00:28,PAID_SUCCESS
11939,"118,168","214,662",1100889695,2017-11-11 21:52:50,2017-11-11 21:54:47,CANCEL
11940,"118,362","215,004",1100889844,2017-11-11 23:02:49,2017-11-11 23:03:27,CANCEL
11941,"118,561","169,883",1100861848,2017-11-11 23:47:45,2017-11-11 23:47:45,PENDING
11942,"119,321","217,362",1100890624,2017-11-13 14:15:24,2017-11-13 14:40:35,PAID_SUCCESS
11943,"120,061","218,702",1100890996,2017-11-14 20:50:53,2017-11-14 20:50:53,PENDING
11944,"121,121","219,903",1100891668,2017-11-18 10:05:16,2017-11-18 10:05:16,PENDING
11945,"123,061","226,222",1100893313,2017-11-22 10:27:10,2017-11-22 10:40:56,PAID_SUCCESS
11946,"123,441","227,282",1100893638,2017-11-23 13:07:36,2017-11-23 13:19:31,PAID_SUCCESS
11947,"123,641","227,722",1100893862,2017-11-23 22:12:18,2017-11-23 22:12:18,PENDING
11948,"123,901","76,584",1100894599,2017-11-25 20:29:01,2017-11-25 22:15:24,PAID_SUCCESS
11949,"124,681","41,753",1100752924,2017-11-28 14:10:50,2017-11-28 14:45:56,CANCEL
11950,"125,341","231,882",1100895816,2017-11-29 14:32:52,2017-11-29 14:41:55,PAID_SUCCESS
11951,"125,421","143,345",1100855052,2017-11-29 18:58:20,2017-11-29 18:58:20,PENDING
11952,"125,944","203,942",1100887409,2017-12-01 00:02:08,2017-12-01 00:01:50,PAID_SUCCESS

รายการสั่งซื้อที่สำเร็จ (Paid_Success)

In [41]:
order = read_csv('../data_20180120/order.csv')

df = pd.DataFrame(order)

df[df['STATUS'] == "PAID_SUCCESS"]

,"﻿""ORDER_ID""",CUSTOMER_ID,BPCODE,CREATE_DATE,UPDATE_DATE,STATUS
2,"2,321","4,223",1100702550,2015-10-16 15:36:42,2015-10-16 15:42:23,PAID_SUCCESS
6,"2,481","2,509",1100605014,2015-10-18 20:50:15,2015-10-18 20:58:13,PAID_SUCCESS
10,"2,781","5,445",1100703863,2015-10-26 11:22:23,2015-10-26 11:25:26,PAID_SUCCESS
12,"3,202","8,263",1100561933,2015-11-01 16:44:23,2015-11-01 16:46:12,PAID_SUCCESS
20,"3,962","10,702",1100708595,2015-11-11 10:22:41,2015-11-11 10:33:29,PAID_SUCCESS
21,"4,001","10,722",1100708626,2015-11-11 13:44:02,2015-11-12 13:53:06,PAID_SUCCESS
26,"4,461","11,804",1100655391,2015-11-16 18:46:49,2015-11-16 18:52:36,PAID_SUCCESS
28,"4,701","12,142",1100710303,2015-11-18 10:41:48,2015-11-19 13:49:31,PAID_SUCCESS
29,"4,941","12,863",1100710868,2015-11-21 08:39:49,2015-11-21 08:42:02,PAID_SUCCESS
32,"5,241","13,464",1100711990,2015-11-24 06:40:31,2015-11-24 07:03:11,PAID_SUCCESS
35,"5,343","13,830",1100712197,2015-11-25 11:42:05,2015-11-25 11:45:58,PAID_SUCCESS
37,"5,441","3,124",1100704391,2015-11-27 06:22:57,2015-11-27 06:27:40,PAID_SUCCESS
39,"5,724","14,837",1100707138,2015-12-01 10:29:00,2015-12-01 10:30:46,PAID_SUCCESS
40,"5,741","15,006",1100713925,2015-12-01 11:30:38,2015-12-01 19:05:25,PAID_SUCCESS
41,"5,742","15,012",1100713938,2015-12-01 11:45:06,2015-12-01 11:47:31,PAID_SUCCESS
43,"5,822","15,006",1100713925,2015-12-01 18:16:29,2015-12-01 19:40:50,PAID_SUCCESS
44,"5,841","15,082",1100714080,2015-12-01 20:25:17,2015-12-01 20:31:38,PAID_SUCCESS
47,"5,961","15,037",1100714092,2015-12-02 13:21:32,2015-12-02 13:32:13,PAID_SUCCESS
51,"6,041","15,309",1100714293,2015-12-03 11:38:34,2015-12-03 11:40:35,PAID_SUCCESS
57,"6,361","16,222",1100715592,2015-12-07 14:59:47,2015-12-07 15:09:57,PAID_SUCCESS
59,"6,482","16,367",1100715869,2015-12-08 13:10:01,2015-12-08 13:15:02,PAID_SUCCESS
65,"2,121",21,1100658148,2015-10-15 11:49:08,2015-10-15 11:51:54,PAID_SUCCESS
66,"2,122",21,1100658148,2015-10-15 11:58:02,2015-10-15 12:00:09,PAID_SUCCESS
72,"2,462","4,725",1100652466,2015-10-18 16:26:24,2015-10-18 16:35:15,PAID_SUCCESS
74,"2,661","5,547",1100643684,2015-10-22 14:46:14,2015-10-22 14:58:20,PAID_SUCCESS
82,"3,281","8,722",1100707010,2015-11-03 14:26:06,2015-11-03 14:54:06,PAID_SUCCESS
84,"3,522","9,362",1100671979,2015-11-06 12:30:21,2015-11-06 12:31:50,PAID_SUCCESS
99,"4,381","11,727",1100709922,2015-11-16 11:43:23,2015-11-16 11:55:01,PAID_SUCCESS
100,"4,401","5,066",1100689191,2015-11-16 13:05:01,2015-11-16 13:06:51,PAID_SUCCESS
103,"4,601","12,063",1100710251,2015-11-17 19:49:30,2015-11-17 19:53:32,PAID_SUCCESS
...,...,...,...,...,...,...
11874,"112,761","203,462",1100886811,2017-11-03 14:04:28,2017-11-03 23:45:46,PAID_SUCCESS
11881,"122,122","224,182",1100892779,2017-11-20 13:21:29,2017-11-20 13:28:07,PAID_SUCCESS
11882,"122,221","222,422",1100496090,2017-11-20 15:00:53,2017-11-20 15:04:16,PAID_SUCCESS
11883,"122,222","222,422",1100496090,2017-11-20 15:00:53,2017-11-20 15:08:49,PAID_SUCCESS
11889,"123,781","228,582",1100894128,2017-11-25 07:51:26,2017-11-25 08:00:26,PAID_SUCCESS
11894,"83,183","143,944",1100855468,2017-06-24 01:08:48,2017-06-24 01:23:06,PAID_SUCCESS
11895,"83,322","134,645",1100847847,2017-06-24 20:44:59,2017-06-24 20:53:44,PAID_SUCCESS
11896,"84,761","140,503",1100858555,2017-07-03 21:16:30,2017-07-03 21:21:20,PAID_SUCCESS
11898,"87,361","151,007",1100861908,2017-07-20 08:46:37,2017-07-20 08:57:31,PAID_SUCCESS
11899,"87,781","121,443",1100836463,2017-07-23 18:45:51,2017-07-23 18:48:04,PAID_SUCCESS
11902,"89,742","97,822",1100815868,2017-08-07 22:16:15,2017-08-07 22:19:40,PAID_SUCCESS
11904,"90,001","154,623",1100459139,2017-08-09 13:27:16,2017-08-09 13:30:08,PAID_SUCCESS
11905,"90,061","154,771",1100867134,2017-08-09 16:23:34,2017-08-09 16:39:19,PAID_SUCCESS
11909,"91,881","158,724",1100870175,2017-08-22 10:50:11,2017-08-22 11:23:05,PAID_SUCCESS
11910,"93,121","160,502",1100871621,2017-08-28 21:38:33,2017-08-28 21:44:42,PAID_SUCCESS
11912,"94,043","162,362",1100711557,2017-08-31 10:46:27,2017-08-31 10:51:09,PAID_SUCCESS
11917,"99,441","176,002",1100877015,2017-09-20 21:55:34,2017-09-20 22:00:39,PAID_SUCCESS
11922,"105,341","136,982",1100852919,2017-10-09 20:05:18,2017-10-09 20:18:41,PAID_SUCCESS
11924,"105,842","184,782",1100881270,2017-10-10 20:00:48,2017-10-10 23:33:33,PAID_SUCCESS
11925,"105,901","27,468",1100731690,2017-10-10 21:03:28,2017-10-10 21:21:12,PAID_SUCCESS
11926,"108,861","195,142",1100883956,2017-10-21 02:12:35,2017-10-21 10:53:18,PAID_SUCCESS
11927,"108,882","121,343",1100559973,2017-10-21 08:46:30,2017-10-21 08:53:17,PAID_SUCCESS
11934,"115,701","212,963",1100889388,2017-11-10 20:07:54,2017-11-11 06:37:18,PAID_SUCCESS
11938,"118,164","215,483",1100889933,2017-11-11 21:49:36,2017-11-11 22:00:28,PAID_SUCCESS
11942,"119,321","217,362",1100890624,2017-11-13 14:15:24,2017-11-13 14:40:35,PAID_SUCCESS
11945,"123,061","226,222",1100893313,2017-11-22 10:27:10,2017-11-22 10:40:56,PAID_SUCCESS
11946,"123,441","227,282",1100893638,2017-11-23 13:07:36,2017-11-23 13:19:31,PAID_SUCCESS
11948,"123,901","76,584",1100894599,2017-11-25 20:29:01,2017-11-25 22:15:24,PAID_SUCCESS
11950,"125,341","231,882",1100895816,2017-11-29 14:32:52,2017-11-29 14:41:55,PAID_SUCCESS
11952,"125,944","203,942",1100887409,2017-12-01 00:02:08,2017-12-01 00:01:50,PAID_SUCCESS

รายการสั่งซื้อที่รอ (Pending)

In [29]:
order = read_csv('../data_20180120/order.csv')

df = pd.DataFrame(order)

df[df['STATUS'] == "PENDING"]

,"﻿""ORDER_ID""",CUSTOMER_ID,BPCODE,CREATE_DATE,UPDATE_DATE,STATUS
0,"2,024",22,1100700373,2015-10-05 21:05:45,2015-10-05 21:05:45,PENDING
1,"2,241","4,122",1100702444,2015-10-15 18:51:08,2015-10-15 19:03:44,PENDING
3,"2,341","4,122",1100702444,2015-10-16 23:45:30,2015-10-16 23:54:33,PENDING
4,"2,422","4,527",1100702884,2015-10-17 18:35:16,2015-10-17 18:45:13,PENDING
5,"2,442","4,462",1100702709,2015-10-18 15:41:07,2015-10-18 15:50:14,PENDING
7,"2,561","2,784",1100686150,2015-10-20 13:37:30,2015-10-20 13:45:41,PENDING
8,"2,641","5,509",1100703880,2015-10-22 13:34:21,2015-10-22 13:44:58,PENDING
9,"2,682","5,805",1100704086,2015-10-23 13:38:16,2015-10-23 13:38:16,PENDING
11,"3,121","8,064",1100662011,2015-10-31 16:47:46,2015-10-31 16:47:46,PENDING
13,"3,261","8,525",1100704444,2015-11-02 16:43:18,2015-11-02 16:50:34,PENDING
14,"3,262","8,529",1100706894,2015-11-02 16:52:58,2015-11-02 16:52:58,PENDING
15,"3,341","8,724",1100707006,2015-11-03 16:47:02,2015-11-03 16:55:40,PENDING
16,"3,403","2,429",1100697318,2015-11-04 14:44:23,2015-11-04 14:55:43,PENDING
17,"3,461","9,104",1100707277,2015-11-05 23:49:50,2015-11-05 23:49:50,PENDING
18,"3,681","4,802",1100707987,2015-11-08 14:23:58,2015-11-08 14:31:09,PENDING
19,"3,781","10,366",1100708439,2015-11-09 20:58:15,2015-11-09 20:58:15,PENDING
22,"4,021","10,782",1100708678,2015-11-11 16:00:42,2015-11-11 16:06:57,PENDING
36,"5,361","13,786",1100546197,2015-11-25 22:57:09,2015-11-25 22:57:09,PENDING
45,"5,881","14,648",1100713155,2015-12-01 22:04:17,2015-12-01 22:04:17,PENDING
48,"5,962","6,711",1100462899,2015-12-02 13:24:54,2015-12-02 13:24:54,PENDING
52,"6,064","10,550",1100478964,2015-12-03 20:47:33,2015-12-03 20:47:33,PENDING
61,"6,541","2,412",1100463792,2015-12-09 10:25:56,2015-12-09 10:25:56,PENDING
62,"2,061",22,1100700373,2015-10-06 23:36:03,2015-10-06 23:36:03,PENDING
64,"2,103",21,1100658148,2015-10-15 09:15:28,2015-10-15 09:15:28,PENDING
68,"2,261","4,082",1100695367,2015-10-15 22:55:29,2015-10-15 22:58:45,PENDING
69,"2,262","4,082",1100695367,2015-10-15 22:55:29,2015-10-15 22:55:29,PENDING
70,"2,281",22,1100700373,2015-10-16 11:31:44,2015-10-16 11:31:44,PENDING
71,"2,381","4,444",1100702677,2015-10-17 13:23:54,2015-10-17 13:30:09,PENDING
73,"2,501","4,991",1100703519,2015-10-19 21:50:28,2015-10-19 22:00:40,PENDING
75,"2,801","6,645",1100705151,2015-10-26 14:39:09,2015-10-26 14:48:51,PENDING
...,...,...,...,...,...,...
11890,"124,721","41,753",1100752924,2017-11-28 14:46:22,2017-11-28 14:46:22,PENDING
11891,"139,023","249,722",1100905088,2017-12-29 22:08:24,2017-12-29 22:08:24,PENDING
11892,"139,882","252,942",1100907622,2018-01-02 22:44:19,2018-01-02 22:44:19,PENDING
11897,"87,341","151,162",1100862031,2017-07-20 05:17:58,2017-07-20 05:17:58,PENDING
11900,"88,981","153,508",1100865593,2017-08-02 11:59:53,2017-08-02 11:59:53,PENDING
11903,"89,781","154,526",1100866917,2017-08-08 12:51:31,2017-08-08 12:51:31,PENDING
11906,"90,701","21,568",1100725301,2017-08-13 20:28:08,2017-08-13 20:28:08,PENDING
11907,"91,281","156,882",1100869016,2017-08-18 07:45:19,2017-08-18 07:45:19,PENDING
11908,"91,283","75,508",1100869178,2017-08-18 08:32:40,2017-08-18 08:32:40,PENDING
11911,"94,001","162,684",1100559825,2017-08-31 08:01:36,2017-08-31 08:01:36,PENDING
11914,"99,301","168,362",1100874536,2017-09-20 14:25:20,2017-09-20 14:25:20,PENDING
11915,"99,361","175,682",1100876924,2017-09-20 16:18:56,2017-09-20 16:18:56,PENDING
11916,"99,403","169,922",1100877003,2017-09-20 20:28:40,2017-09-20 20:28:40,PENDING
11918,"100,361","175,782",1100876948,2017-09-23 18:33:26,2017-09-23 18:33:26,PENDING
11919,"100,381","176,502",1100874243,2017-09-23 19:07:57,2017-09-23 19:07:57,PENDING
11920,"101,961","166,122",1100864344,2017-09-28 10:28:23,2017-09-28 10:28:23,PENDING
11921,"103,761","2,082",1100500779,2017-10-03 14:53:11,2017-10-03 14:53:11,PENDING
11923,"105,821","188,883",1100881820,2017-10-10 19:17:49,2017-10-10 19:17:49,PENDING
11928,"108,941","197,902",1100884598,2017-10-21 11:42:33,2017-10-21 11:42:33,PENDING
11929,"109,282","199,222",1100885270,2017-10-22 22:09:34,2017-10-22 22:09:34,PENDING
11930,"109,982","2,082",1100500779,2017-10-25 16:57:14,2017-10-25 16:57:14,PENDING
11931,"112,081","205,142",1100887427,2017-11-01 15:58:57,2017-11-01 15:58:57,PENDING
11932,"112,401","206,362",1100887613,2017-11-02 12:18:49,2017-11-02 12:18:49,PENDING
11933,"113,741","209,022",1100888598,2017-11-06 14:14:01,2017-11-06 14:14:01,PENDING
11936,"116,205","176,764",1100787082,2017-11-11 08:26:59,2017-11-11 08:26:59,PENDING
11941,"118,561","169,883",1100861848,2017-11-11 23:47:45,2017-11-11 23:47:45,PENDING
11943,"120,061","218,702",1100890996,2017-11-14 20:50:53,2017-11-14 20:50:53,PENDING
11944,"121,121","219,903",1100891668,2017-11-18 10:05:16,2017-11-18 10:05:16,PENDING
11947,"123,641","227,722",1100893862,2017-11-23 22:12:18,2017-11-23 22:12:18,PENDING
11951,"125,421","143,345",1100855052,2017-11-29 18:58:20,2017-11-29 18:58:20,PENDING

รายการสั่งซื้อที่ยกเลิก (Cancel)

In [30]:
order = read_csv('../data_20180120/order.csv')

df = pd.DataFrame(order)

df[df['STATUS'] == "CANCEL"]

,"﻿""ORDER_ID""",CUSTOMER_ID,BPCODE,CREATE_DATE,UPDATE_DATE,STATUS
33,"5,341","13,842",1100712196,2015-11-25 11:31:48,2017-06-20 10:54:31,CANCEL
34,"5,342","13,842",1100712196,2015-11-25 11:31:48,2017-06-20 10:54:31,CANCEL
38,"5,561","13,842",1100712196,2015-11-29 12:56:00,2017-06-20 10:55:13,CANCEL
427,"9,441","13,842",1100712196,2016-01-01 20:05:27,2017-06-20 10:55:55,CANCEL
429,"9,481","13,842",1100712196,2016-01-02 12:00:38,2017-06-20 10:55:47,CANCEL
438,"10,642","13,842",1100712196,2016-01-13 09:53:00,2017-06-20 10:54:56,CANCEL
442,"11,161","13,842",1100712196,2016-01-17 12:06:17,2017-06-20 10:54:43,CANCEL
474,"9,001","13,842",1100712196,2015-12-30 13:40:01,2017-06-20 10:56:02,CANCEL
530,"7,981","11,294",1100385214,2015-12-24 01:29:08,2017-10-21 15:23:50,CANCEL
741,"9,161","21,245",1100715726,2015-12-30 22:52:24,2017-09-28 14:22:16,CANCEL
748,"10,361","13,842",1100712196,2016-01-11 16:50:53,2017-06-20 10:55:39,CANCEL
1079,"14,903","29,644",1100735017,2016-02-14 14:43:41,2017-11-10 23:38:22,CANCEL
1211,"13,881","28,702",1100732913,2016-02-05 13:50:15,2017-08-19 07:15:50,CANCEL
1341,"19,301","36,842",1100747096,2016-04-05 06:41:59,2017-12-02 21:52:11,CANCEL
1498,"21,106","8,885",1100671948,2016-04-19 14:03:51,2017-12-03 11:24:34,CANCEL
1499,"21,107","8,885",1100671948,2016-04-19 14:25:01,2017-12-03 11:22:14,CANCEL
1685,"19,281","36,842",1100747096,2016-04-05 01:18:20,2017-12-02 21:54:36,CANCEL
1687,"19,401","31,213",1100584027,2016-04-06 11:22:32,2017-06-28 19:07:14,CANCEL
1747,"24,801","45,562",1100758999,2016-05-23 15:19:34,2017-06-09 11:25:54,CANCEL
1778,"21,103","8,885",1100671948,2016-04-19 13:49:32,2017-12-03 11:24:58,CANCEL
1845,"21,105","8,885",1100671948,2016-04-19 14:00:16,2017-12-03 11:24:45,CANCEL
1910,"27,284","46,388",1100656747,2016-06-11 14:24:56,2017-05-31 21:12:37,CANCEL
1911,"27,285","46,388",1100656747,2016-06-11 14:54:44,2017-05-31 21:12:32,CANCEL
1912,"27,288","46,388",1100656747,2016-06-11 15:05:46,2017-05-31 21:12:14,CANCEL
1976,"27,281","46,388",1100656747,2016-06-11 13:49:14,2017-05-31 21:11:56,CANCEL
2027,"25,981","46,388",1100656747,2016-06-03 08:54:24,2017-05-31 21:11:49,CANCEL
2063,"28,281","25,503",1100526827,2016-06-19 07:35:54,2017-06-01 00:33:45,CANCEL
2163,"26,782","46,709",1100629436,2016-06-08 14:19:48,2017-05-22 10:24:36,CANCEL
2171,"27,282","46,388",1100656747,2016-06-11 14:04:25,2017-05-31 21:12:47,CANCEL
2172,"27,283","46,388",1100656747,2016-06-11 14:06:45,2017-05-31 21:12:42,CANCEL
...,...,...,...,...,...,...
11786,"101,022","169,603",1100878351,2017-09-25 20:57:26,2017-11-20 11:37:00,CANCEL
11787,"101,023","169,603",1100878351,2017-09-25 20:57:26,2017-11-20 11:37:00,CANCEL
11788,"102,241","180,742",1100878916,2017-09-29 00:20:51,2017-09-29 00:25:18,CANCEL
11799,"115,821","168,022",1100874239,2017-11-11 00:04:11,2017-11-11 00:12:19,CANCEL
11800,"115,822","213,344",1100889415,2017-11-11 00:04:17,2017-11-11 00:16:16,CANCEL
11809,"117,243","214,742",1100886794,2017-11-11 16:24:17,2017-11-11 16:26:13,CANCEL
11812,"117,501","146,602",1100858658,2017-11-11 17:50:15,2017-11-16 20:57:08,CANCEL
11819,"138,522","47,002",1100905651,2017-12-28 22:21:10,2017-12-28 22:32:41,CANCEL
11820,"138,921","231,763",1100875483,2017-12-29 20:43:26,2017-12-30 06:46:24,CANCEL
11823,"140,001","46,486",1100907630,2018-01-03 11:45:29,2018-01-03 12:42:19,CANCEL
11824,"141,341","255,122",1100908872,2018-01-07 20:57:26,2018-01-07 20:55:03,CANCEL
11825,"141,342","255,122",1100908872,2018-01-07 20:57:26,2018-01-07 20:55:03,CANCEL
11826,"83,141","143,605",1100855348,2017-06-23 15:40:45,2017-06-23 15:41:16,CANCEL
11830,"83,741","144,522",1100856638,2017-06-27 11:56:10,2017-06-27 11:56:44,CANCEL
11831,"84,004","139,643",1100854815,2017-06-28 22:19:17,2017-06-28 22:24:18,CANCEL
11832,"84,270","140,382",1100853390,2017-06-30 14:07:26,2017-11-13 17:55:13,CANCEL
11834,"84,661","146,062",1100858410,2017-07-03 11:40:22,2017-07-03 11:42:46,CANCEL
11857,"95,561","63,042",1100779786,2017-09-07 20:18:31,2017-09-07 20:19:14,CANCEL
11860,"97,021","169,982",1100875140,2017-09-12 01:15:28,2017-09-12 01:16:29,CANCEL
11868,"106,201","170,623",1100875285,2017-10-11 00:57:20,2017-10-11 01:00:50,CANCEL
11876,"116,921","204,802",1100887269,2017-11-11 14:37:49,2017-11-11 14:42:19,CANCEL
11878,"117,384","214,722",1100804833,2017-11-11 17:06:59,2017-11-11 17:15:28,CANCEL
11893,"83,182","131,982",1100851287,2017-06-24 00:49:16,2017-06-24 00:58:45,CANCEL
11901,"89,302","153,946",1100866064,2017-08-05 00:09:17,2017-08-24 22:15:32,CANCEL
11913,"95,041","165,382",1100873576,2017-09-05 00:53:27,2017-09-05 00:55:12,CANCEL
11935,"116,061","152,723",1100889427,2017-11-11 06:27:29,2017-11-11 06:27:08,CANCEL
11937,"116,941","204,802",1100887269,2017-11-11 14:37:58,2017-11-11 14:42:11,CANCEL
11939,"118,168","214,662",1100889695,2017-11-11 21:52:50,2017-11-11 21:54:47,CANCEL
11940,"118,362","215,004",1100889844,2017-11-11 23:02:49,2017-11-11 23:03:27,CANCEL
11949,"124,681","41,753",1100752924,2017-11-28 14:10:50,2017-11-28 14:45:56,CANCEL